global using AutoMapper;
global using MediatR;
global using Microsoft.EntityFrameworkCore;
global using UdemyNewMicroservice.Shared;
global using UdemyNewMicroservice.Shared.Extensions;
global using FluentValidation;
global using MassTransit;
global using System.Net;
global using UdemyNewMicroservice.Catalog.Api.Features.Categories.Dtos;