@baseAdrress = http://localhost:5056

GET {{baseAdrress}}/api/categories
Accept: application/json

###
POST {{baseAdrress}}/api/categories
Accept: application/json
Content-Type: application/json
{
    "name": "Category 3"
}
